name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-tidy
        run: |
          sudo apt-get install -y clang-tidy
          find . -name '*.cpp' | xargs clang-tidy
